---

name: Ubuntu2204-CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - '**/*.md'
      - .gitignore
      - ./meta/main.yml

jobs:
  ubuntu2204-ci:
    uses: philnewm/ansible-role-repo-control/.github/workflows/molecule-ci-vbox.yml@main
    with:
      scenario_name: ubuntu2204

...
