---

name: Blog publishing controller
    
on:
  workflow_dispatch:
  push:
    branches:
      - publish
      - draft
    paths:
      - "**/resources/**"
      - "**.md"
      - "!TODO.md"
      - "!README.md"
      - "!.gitignore"
      - "!.obsidian/**"

env:
  GH_TOKEN: ${{ github.token }}

permissions:
  contents: read

jobs:
  get-changed-md-files:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest file changes from ${{ github.repository}}/refs/heads/${{ github.ref_name }}
        # Warning will brake if commas (",") are used in filepaths
        # TODO test if this works for multiple commits as well
        id: latest-changes
        run: |
          # INFO Get commit hashes from two latest pushes
          read HEAD_SHA BASE_SHA < <(gh api repos/${{ github.repository}}/events --jq '[ .[] | select(.type=="PushEvent" and .payload.ref == "refs/heads/${{ github.ref_name }}") ][0] | [.payload.head, .payload.before] | join(" ")')

          echo "Comparing changes between $BASE_SHA and $HEAD_SHA"

          CHANGES=$(gh api repos/philnewm/blog-articles/compare/$BASE_SHA...$HEAD_SHA --jq '
            {
              added:   [ .files[] | select(.status=="added") | .filename ],
              edited:  [ .files[] | select(.status=="modified") | .filename ],
              removed: [ .files[] | select(.status=="removed") | .filename ]
            }')

          # INFO compact (-c) jq for single line strings
          ADDED_FILES=$(echo "$CHANGES" | jq -c '.added | join(",")')
          EDITED_FILES=$(echo "$CHANGES" | jq -c '.edited | join(",")')
          REMOVED_FILES=$(echo "$CHANGES" | jq -c '.removed | join(",")')

          echo "added_files=$ADDED_FILES" >> $GITHUB_OUTPUT
          echo "edited_files=$EDITED_FILES" >> $GITHUB_OUTPUT
          echo "removed_files=$REMOVED_FILES" >> $GITHUB_OUTPUT

      - name: Debug file changes sorted
        run: |
          echo "Added files: ${{ steps.latest-changes.outputs.added_files }}"
          echo "Edited files: ${{ steps.latest-changes.outputs.edited_files }}"
          echo "Removed files: ${{ steps.latest-changes.outputs.removed_files }}"


  # get-front-matter:
  #   uses: philnewm/blog-articles/.github/workflows/front_matter_processor.yml

  # run-ci:
  #   if: ${{ jobs.get-fron-matter.outputs.ci_file }}

