---

name: Blog publishing controller
    
on:
  workflow_dispatch:
  push:
    branches:
      - publish
      - draft
    paths:
      - "**/resources/**"
      - "**.md"
      - "**/workflows/**"
      - "!TODO.md"
      - "!README.md"
      - "!.gitignore"
      - "!.obsidian/**"

env:
  GH_TOKEN: ${{ github.token }}

permissions:
  contents: read

jobs:
  get-changed-md-files:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest file changes from ${{ github.repository}}/refs/heads/${{ github.ref_name }}
        # Warning will brake if commas (",") are used in filepaths
        id: latest-changes
        run: |
          # INFO repo events endpoint is not meant for realtime usage - see https://docs.github.com/en/rest/activity/events?apiVersion=2022-11-28#list-repository-events
          # read HEAD_SHA BASE_SHA < <(gh api repos/philnewm/blog-articles/events --jq '[ .[] | select(.type=="PushEvent" and .payload.ref == "refs/heads/${{ github.ref_name }}") ][0] | [.payload.head, .payload.before] | join(" ")')

          set -x

          LATEST_COMMIT_SHA=$(gh api repos/philnewm/blog-articles/commits?sha=draft --jq '.[0].sha')
          LATEST_PUSH_LATEST_COMMIT_SHA=${{ vars.LATEST_PUSH_COMMIT_SHA }}

          echo "latest_commit_sha=$LATEST_COMMIT_SHA" >> $GITHUB_OUTPUT
          echo "Latest Commit: $LATEST_COMMIT_SHA"
          echo "Second latest push commit SHA: $LATEST_PUSH_LATEST_COMMIT_SHA"

          EXCLUDE_LIST=("README.md" "TODO.md" ".obsidian/")
          CHANGES=$(gh api repos/philnewm/blog-articles/compare/$LATEST_PUSH_LATEST_COMMIT_SHA...$LATEST_COMMIT_SHA)
          EXCLUDE_JSON=$(printf '%s\n' "${EXCLUDE_LIST[@]}" | jq -R . | jq -s .)
          FILTERED_CHANGES=$(echo "$CHANGES" | jq --argjson exclude_list "$EXCLUDE_JSON" '
            def is_excluded($filename):
              reduce $exclude_list[] as $excl (true; . and ($filename | contains($excl) | not));

            {
              added: [ .files[] | select(.status == "added" and (is_excluded(.filename))) | .filename ],
              modified: [ .files[] | select(.status == "modified" and (is_excluded(.filename))) | .filename ],
              removed: [ .files[] | select(.status == "removed" and (is_excluded(.filename))) | .filename ]
            }
          ')

          echo "Filtered changes: $FILTERED_CHANGES"

          ADDED_FILES=()
          MODIFIED_FILES=()
          REMOVED_FILES=()

          classify_file() {
            local file_path="$1"
            local file_status="$2"

            echo "Classifying file: $file_path with status: $file_status"

            if [[ "$file_path" == *.md ]]; then
              echo "File is a markdown file"
              case "$file_status" in
                "added") ADDED_FILES+=("$file_path") ;;
                "modified") MODIFIED_FILES+=("$file_path") ;;
                "removed") REMOVED_FILES+=("$file_path") ;;
              esac
            fi

            if [[ "$file_path" == *"/resources"* ]]; then
              echo "File is in resources folder"
              stripped_path="${file_path%%/resources*}"
              # WARNING breaks if paths doesn't exist anymore
              md_files=$(gh api repos/philnewm/blog-articles/contents/"$stripped_path"?ref=${{ github.ref_name }} | jq -r '.[] | select(.name | endswith(".md")) | .name')

              echo $file_path

              for md_file in $md_files; do
                case "$file_status" in
                  "added") ADDED_FILES+=("$stripped_path/$md_file") ;;
                  "modified") MODIFIED_FILES+=("$stripped_path/$md_file") ;;
                  "removed") REMOVED_FILES+=("$stripped_path/$md_file") ;;
                esac
              done
            fi

            if [[ "$file_path" == *"workflows"* && "$file_path" == *.yml ]]; then
              # res_path=$(yq eval '.env.RES_PATH // ""' "$file_path" 2>/dev/null)
              res_path=""

              if [[ -n "$res_path" ]]; then
                echo "File is a workflow file"
                stripped_path="${res_path///resources/}"
                # WARNING breaks if paths doesn't exist anymore
                md_files=$(gh api repos/philnewm/blog-articles/contents/"$stripped_path"?ref=${{ github.ref_name }} | jq -r '.[] | select(.name | endswith(".md")) | .name')

                for md_file in $md_files; do
                  case "$file_status" in
                    "added") ADDED_FILES+=("$stripped_path/$md_file") ;;
                    "modified") MODIFIED_FILES+=("$stripped_path/$md_file") ;;
                    "removed") REMOVED_FILES+=("$stripped_path/$md_file") ;;
                  esac
                done
              fi
            fi
          }

          # INFO Iterate over all changed files and classify them
          for file in $(echo "$FILTERED_CHANGES" | jq -r '.added[]'); do
            classify_file "$file" "added"
          done
          for file in $(echo "$FILTERED_CHANGES" | jq -r '.modified[]'); do
            classify_file "$file" "modified"
          done
          for file in $(echo "$FILTERED_CHANGES" | jq -r '.removed[]'); do
            classify_file "$file" "removed"
          done

          ADDED_FILES_STR=$(IFS=,; echo "${ADDED_FILES[*]}")
          MODIFIED_FILES_STR=$(IFS=,; echo "${MODIFIED_FILES[*]}")
          REMOVED_FILES_STR=$(IFS=,; echo "${REMOVED_FILES[*]}")

          echo "added_files=$ADDED_FILES_STR" >> $GITHUB_OUTPUT
          echo "edited_files=$MODIFIED_FILES_STR" >> $GITHUB_OUTPUT
          echo "removed_files=$REMOVED_FILES_STR" >> $GITHUB_OUTPUT

          echo "Added files: $ADDED_FILES_STR"
          echo "Edited files: $MODIFIED_FILES_STR"
          echo "Removed files: $REMOVED_FILES_STR"

      - name: Debug file changes sorted
        run: |
          echo "Added files: ${{ steps.latest-changes.outputs.added_files }}"
          echo "Edited files: ${{ steps.latest-changes.outputs.edited_files }}"
          echo "Removed files: ${{ steps.latest-changes.outputs.removed_files }}"

      - name: Update latest push commit sha
        run: |
          echo "Latest push commit sha: ${{ steps.latest-changes.outputs.latest_commit_sha }}"
          gh variable set LATEST_PUSH_COMMIT_SHA --repo ${{ github.repository}} --body ${{ steps.latest-changes.outputs.latest_commit_sha }}

  # get-front-matter:
  #   uses: philnewm/blog-articles/.github/workflows/front_matter_processor.yml

  # run-ci:
  #   if: ${{ jobs.get-fron-matter.outputs.ci_file }}

