---

name: Dev.to Pipeline

on:
  # TODO remove this trigger after debugging
  workflow_dispatch:
  push:
    branches:
      - publish

  workflow_run:
      workflows:
      - getting-started-ci
      types:
      - completed

permissions:
  contents: read

env:
  PYTHON_VERSION: "3.12"
  URL: "raw.githubusercontent.com/${{ github.repository }}/${{ github.ref_name }}"
  TARGET_REPO: "philnewm.github.io"
  TARGET_PREFIX: "https://philnewm.github.io/"

jobs:
  collect-markdown-files:
    runs-on: ubuntu-latest
    outputs:
      files_added: ${{ steps.compare-files.outputs.files_added }}
      files_removed: ${{ steps.compare-files.outputs.files_removed }}

    steps:
      # TODO cleanup this query mess
      - name: Get markdown files from ${{ github.repository}}
        id: get-source-md-files
        # TODO change to publish branch when implemented
        run: |
          IGNORED_FILES_JSON=$(jq -R -c 'split(",")' <<< "${{ vars.IGNORED_FILES }}")

          md_files_json=$(gh api repos/${{ github.repository }}/git/trees/${{ github.ref_name }}?recursive=1 --jq '[.tree[].path | select(endswith(".md"))]')
          md_files_json=$(echo $md_files_json | jq --argjson ignored "$IGNORED_FILES_JSON" 'map(select(. as $file | $ignored | index($file) | not))')
          md_files_str=$(echo $md_files_json | jq -c)

          echo "source_files=$md_files_str" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Get article canonical_urls from dev.to
        id: get-target-articles
        run: |
          articles_map=$(curl -H "api-key: ${{ secrets.DEVTO_KEY }}" https://dev.to/api/articles/me/all | jq -c 'map({(.canonical_url): .id}) | add')
          articles_string=$(echo $articles_map | jq -c)

          echo "articles_map=$articles_string" >> $GITHUB_OUTPUT

      - name: Debug output
        run: |
          echo "source_files=$(echo '${{ steps.get-source-md-files.outputs.source_files }}' | jq -r)"
          echo "target_articles=$(echo '${{ steps.get-target-articles.outputs.articles_map }}' | jq -r)"

      - name: Compare files
        id: compare-articles
        env:
          SOURCE: "${{ steps.get-source-md-files.outputs.source_files }}"
          TARGET: "${{ steps.get-target-articles.outputs.articles_map }}"
          BASE_URL: "https://raw.githubusercontent.com/${{ github.repository }}/refs/heads/${{ github.ref_name }}/"
        run: |
          normalized_source_files=$(echo '${{ env.SOURCE }}' | jq -c 'split(" ") | map(sub("\\.md$"; ""))')
          normalized_target_articles=$(echo '${{ env.TARGET }}' | jq -c 'to_entries | map({ key: ( .key | sub("^${{ env.TARGET_PREFIX }}"; "") | sub("/$"; "") ), value: .value }) | from_entries')

          echo "normalized_source_files: $normalized_source_files"
          echo "normalized_target_articles: $normalized_target_articles"

          md_to_id_mapping=$(jq -nc \
                      --argjson src "$normalized_source_files" \
                      --argjson tgt "$normalized_target_articles" \
                      '
                      reduce $src[] as $file ({}; 
                        .[$file + ".md"] = if $tgt[$file] then $tgt[$file] else "" end
                      )
                      | reduce ($tgt | keys[]) as $article (.;
                          if not ($src | contains([$article])) then
                            .[""] = $tgt[$article]
                          end
                        )
                      ')

          echo "files_map=$md_to_id_mapping" >> $GITHUB_OUTPUT

          files_csv=$(echo "${{ env.SOURCE }}" | jq -r --arg base "${{ env.BASE_URL }}" '[.[] | $base + .] | join(",")')
          echo "files_csv=$files_csv" >> $GITHUB_OUTPUT

      - name: Debug output
        run: |
          echo "files_map=$(echo '${{ steps.compare-articles.outputs.files_map }}' | jq -r)"
          echo "source_files=$(echo '${{ steps.compare-articles.outputs.files_csv }}' | jq -r)"

      # - name: Convert code and admonitions
      #   if: ${{ steps.compare-titles.outputs.files_added }}
      #   uses: philnewm/markdown-conversion@main
      #   with:
      #     markdown_file_urls: ${{ steps.compare-titles.outputs.files_csv }}
      #     output_dir_code: ${{ github.workspace }}/code

      # - name: Upload gh_output
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: code_output
      #     path: ${{ github.workspace }}/code/*
      #     if-no-files-found: error


  push-to-devto:
    needs:
      - collect-markdown-files
    if: false  # ${{ needs.collect-markdown-files.outputs.files_added || needs.collect-markdown-files.outputs.files_removed }}
    # TODO put back in line after development
    # && github.event.workflow_run.head_branch == 'publish' }}
    runs-on: ubuntu-latest

    steps:
      - name: Get artifacts
        if: ${{ needs.collect-markdown-files.outputs.files_added }}
        uses: actions/download-artifact@v4
        with:
          name: code_output
          path: tmp

      - name: Move artifact to target directory
        if: ${{ needs.collect-markdown-files.outputs.files_added }}
        env:
          FILE_PATHS_ADD: ${{ needs.collect-markdown-files.outputs.files_added }}
        run: |
          mkdir -p site/docs

          readarray -t file_array < <(echo '${{ env.FILE_PATHS_ADD }}' | jq -r '.[]')
          echo "Updating files: ${file_array[@]}"

          for file_path in "${file_array[@]}"; do
            mkdir -p "$(dirname ${{ github.workspace }}/site/docs/$file_path)"
            cp tmp/$(basename $file_path) ${{ github.workspace }}/site/docs/$file_path
          done

          rm -Rf ${{ github.workspace }}/tmp

      - name: Remove obsolete files
        if: ${{ needs.collect-markdown-files.outputs.files_removed }}
        env:
          FILE_PATHS_DEL: ${{ needs.collect-markdown-files.outputs.files_removed }}
        run: |
          readarray -t file_array < <(echo '${{ env.FILE_PATHS_DEL }}' | jq -r '.[]')
          echo "Removing files: ${file_array[@]}"

          for file_path in "${file_array[@]}"; do
            rm -f "/${{ github.workspace }}/site/docs/$file_path"
          done

...
