---

name: Dev.to Pipeline

on:
  # TODO remove this trigger after debugging
  workflow_dispatch:
  push:
    branches:
      - publish

  workflow_run:
      workflows:
      - getting-started-ci
      types:
      - completed

permissions:
  contents: read

env:
  PYTHON_VERSION: "3.12"
  URL: "raw.githubusercontent.com/${{ github.repository }}/${{ github.ref_name }}"
  TARGET_REPO: "philnewm.github.io"
  TARGET_PREFIX: "site/docs/"

jobs:
  collect-markdown-files:
    runs-on: ubuntu-latest
    outputs:
      files_added: ${{ steps.compare-files.outputs.files_added }}
      files_removed: ${{ steps.compare-files.outputs.files_removed }}

    steps:
      # TODO cleanup this query mess
      - name: Get markdown files from ${{ github.repository}}
        id: get-source-md-files
        # TODO change to publish branch when implemented
        run: |
          IGNORED_FILES_JSON=$(jq -R -c 'split(",")' <<< "${{ vars.IGNORED_FILES }}")

          md_files_json=$(gh api repos/${{ github.repository }}/git/trees/${{ github.ref_name }}?recursive=1 --jq '[.tree[].path | select(endswith(".md"))]')
          md_files_json=$(echo $md_files_json | jq --argjson ignored "$IGNORED_FILES_JSON" 'map(select(. as $file | $ignored | index($file) | not))')
          md_files_str=$(echo $md_files_json | jq -c)

          echo "source_files=$md_files_str" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Get article canonical_urls from dev.to
        id: get-target-canonical_urls
        run: |
          canonical_urls=$(curl -H "api-key: ${{ secrets.DEVTO_KEY }}" https://dev.to/api/articles/me/all | jq -c '.[].canonical_url')
          canonical_urls_string=$(echo $canonical_urls | jq -c)

          echo "canonical_urls=$canonical_urls_string" >> $GITHUB_OUTPUT

      - name: Debug output
        run: |
          echo "source_files=$(echo '${{ steps.get-source-md-files.outputs.source_files }}' | jq -r)"
          echo "target_canonical_urls=$(echo '${{ steps.get-target-canonical_urls.outputs.canonical_urls }}' | jq -r)"

      # - name: Compare titles
      #   id: compare-titles
      #   run: |
      #     source_titles=$(echo '${{ steps.get-source-md-files.outputs.titles }}' | jq -r)
      #     target_titles=$(echo '${{ steps.get-target-canonical_urls.outputs.titles }}' | jq -r)

      #     titles_added=$(echo $source_titles $target_titles | jq -s -c '.[0] - .[1]')
      #     titles_removed=$(echo $source_titles $target_titles | jq -s -c '.[1] - .[0]')

      #     echo "titles_added=$files_added" >> $GITHUB_OUTPUT
      #     echo "titles_removed=$files_removed" >> $GITHUB_OUTPUT

      #     base_url="https://raw.githubusercontent.com/${{ github.repository }}/refs/heads/${{ github.ref_name }}/"
      #     titles_csv=$(echo "$files_added" | jq -r --arg base "$base_url" '[.[] | $base + .] | join(",")')
      #     echo "titles_csv=$titles_csv" >> $GITHUB_OUTPUT

      # - name: Debug output
      #   run: |
      #     echo "added_titles=$(echo '${{ steps.compare-titles.outputs.titles_added }}' | jq -r)"
      #     echo "removed_titles=$(echo '${{ steps.compare-titles.outputs.titles_removed }}' | jq -r)"

      # - name: Convert code and admonitions
      #   if: ${{ steps.compare-titles.outputs.titles_added }}
      #   uses: philnewm/markdown-conversion@main
      #   with:
      #     markdown_file_urls: ${{ steps.compare-titles.outputs.titles_csv }}
      #     output_dir_code: ${{ github.workspace }}/code

      # - name: Upload gh_output
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: code_output
      #     path: ${{ github.workspace }}/code/*
      #     if-no-files-found: error


  push-to-devto:
    needs:
      - collect-markdown-files
    if: false  # ${{ needs.collect-markdown-files.outputs.files_added || needs.collect-markdown-files.outputs.files_removed }}
    # TODO put back in line after development
    # && github.event.workflow_run.head_branch == 'publish' }}
    runs-on: ubuntu-latest

    steps:
      - name: Get artifacts
        if: ${{ needs.collect-markdown-files.outputs.files_added }}
        uses: actions/download-artifact@v4
        with:
          name: code_output
          path: tmp

      - name: Move artifact to target directory
        if: ${{ needs.collect-markdown-files.outputs.files_added }}
        env:
          FILE_PATHS_ADD: ${{ needs.collect-markdown-files.outputs.files_added }}
        run: |
          mkdir -p site/docs

          readarray -t file_array < <(echo '${{ env.FILE_PATHS_ADD }}' | jq -r '.[]')
          echo "Updating files: ${file_array[@]}"

          for file_path in "${file_array[@]}"; do
            mkdir -p "$(dirname ${{ github.workspace }}/site/docs/$file_path)"
            cp tmp/$(basename $file_path) ${{ github.workspace }}/site/docs/$file_path
          done

          rm -Rf ${{ github.workspace }}/tmp

      - name: Remove obsolete files
        if: ${{ needs.collect-markdown-files.outputs.files_removed }}
        env:
          FILE_PATHS_DEL: ${{ needs.collect-markdown-files.outputs.files_removed }}
        run: |
          readarray -t file_array < <(echo '${{ env.FILE_PATHS_DEL }}' | jq -r '.[]')
          echo "Removing files: ${file_array[@]}"

          for file_path in "${file_array[@]}"; do
            rm -f "/${{ github.workspace }}/site/docs/$file_path"
          done

...
