---

name: blog-preprocessor

on:
  # TODO remove this trigger after debugging
  workflow_dispatch:
  push:
    branches:
      - publish

  workflow_run:
      workflows:
      - getting-started-ci
      types:
      - completed

permissions:
  contents: read

env:
  PYTHON_VERSION: "3.12"
  URL: "raw.githubusercontent.com/${{ github.repository }}/${{ github.ref_name }}"
  TARGET_REPO: "philnewm.github.io"

jobs:
  collect-markdown-files:
    runs-on: ubuntu-latest
    outputs:
      files_added: ${{ steps.get-markdown-files.outputs.files_added }}
      files_removed: ${{ steps.get-markdown-files.outputs.files_removed }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: philnewm/blog-articles
          fetch-depth: 2

      - name: Get markdown files
        id: get-markdown-files
        env:
          IGNORED_FILES: ${{ vars.IGNORED_FILES }}
        run: |
          IFS=',' read -r -a ignore_array <<< "${{ env.IGNORED_FILES }}"
          mapfile -t files_add < <(git diff --name-only --diff-filter=A HEAD^ HEAD -- '*.md')
          mapfile -t files_del < <(git diff --name-only --diff-filter=D HEAD^ HEAD -- '*.md')

          filter_files() {
              local file_list=("$1")
              local filtered_files=()
              
              for file in "${file_list[@]}"; do
                  for ignored in "${ignore_array[@]}"; do
                      [[ "$file" == "$ignored" ]] && continue 2
                  done
                  filtered_files+=("$file")
              done

              # Convert filtered list to JSON format
              files_json=$(printf '%s\n' "${filtered_files[@]}" | jq -R -s -c 'split("\n")[:-1]')
              echo "$files_json"
          }

          # Check and filter added files
          if [ ${#files_add[@]} -gt 0 ]; then
              files_added_json=$(filter_files "${files_add[@]}")

              echo -e "::notice::Markdown files added:\n\n$($files_added_json | jq -r '.[]')"
              echo "files_added=$files_added_json" >> $GITHUB_OUTPUT
          else
              echo "files_added=''" >> $GITHUB_OUTPUT
              echo "::notice::No added files found."
          fi

          # Check and filter removed files
          if [ ${#files_del[@]} -gt 0 ]; then
              files_removed_json=$(filter_files "${files_del[@]}")

              echo -e "::notice::Markdown files removed:\n\n$($files_added_json | jq -r '.[]')"
              echo "files_removed=$files_removed_json" >> $GITHUB_OUTPUT
          else
              echo "files_removed=''" >> $GITHUB_OUTPUT
              echo "::notice::No removed files found."

          fi

      - name: Show added files if any
        if: ${{ steps.get-markdown-files.outputs.files_added }}
        run: |
          echo "Markdown files from workflow: ${{ toJson(steps.get-markdown-files.outputs.files_added) }}"
          echo "Markdown files from workflow: ${{ fromJson(steps.get-markdown-files.outputs.files_added) }}"
          echo "Markdown files from workflow: ${{ steps.get-markdown-files.outputs.files_added }}"

      - name: Show removed files if any
        if: ${{ steps.get-markdown-files.outputs.files_removed }}
        run: |
          echo "Markdown files from workflow: ${{ toJson(steps.get-markdown-files.outputs.files_removed) }}"
          echo "Markdown files from workflow: ${{ fromJson(steps.get-markdown-files.outputs.files_removed) }}"
          echo "Markdown files from workflow: ${{ steps.get-markdown-files.outputs.files_removed }}"

  convert-markdown:
    needs: collect-markdown-files
    # TODO research if there's some way to check if the output is empty
    if: ${{ needs.collect-markdown-files.outputs.files_added != '[""]' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{ fromJson(needs.collect-markdown-files.outputs.files) }}

    steps:
      - name: Extract file name
        id: extract_filename
        run: |
          filename=$(basename "${{ matrix.file }}")
          echo "filename=$filename" >> $GITHUB_OUTPUT

      - name: Convert code and admonitions
        uses: philnewm/markdown-conversion@main
        env:
          FILE_NAME: ${{ steps.extract_filename.outputs.filename }}
        with:
          domain_url: ${{ env.URL }}
          markdown_file_path: ${{ matrix.file }}
          code: true
          output_file_code: ${{ github.workspace }}/code/${{ env.FILE_NAME }}
          admonitions: true
          output_file_admonitions: ${{ github.workspace }}/admonition/${{ env.FILE_NAME }}

      - name: Upload gh_output
        env:
          FILE_NAME: ${{ steps.extract_filename.outputs.filename }}
        uses: actions/upload-artifact@v4
        with:
          name: gh_output
          path: ${{ github.workspace }}/code/${{ env.FILE_NAME }}
          if-no-files-found: error

      - name: Upload devto_output
        env:
          FILE_NAME: ${{ steps.extract_filename.outputs.filename }}
        uses: actions/upload-artifact@v4
        with:
          name: devto_output
          path: ${{ github.workspace }}/admonition/${{ env.FILE_NAME }}
          if-no-files-found: error

  push-to-pages-repo:
    needs: convert-markdown
    if: false  # ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'publish' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: philnewm/philnewm.github.io
          token: ${{ secrets.PAGES_PAT }}
          fetch-depth: 1

      - name: Get artifacts
        uses: actions/download-artifact@v4
        with:
          name: gh_output
          path: tmp

      - name: Move Artifact to Target Directory
        run: |
          mkdir -p site/docs
          cp tmp/${{ env.FILE_NAME }} /${{ github.workspace }}/site/docs/
          rm -Rf /${{ github.workspace }}/tmp

      - name: Verify Artifact Location
        run: |
          echo "Files in site/docs:"
          ls -l /${{ github.workspace }}/site/docs

      - name: Push new file to pages repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "[Automated] Add text file '${{ env.FILE_NAME }}' repository"
          git push

  push-to-devto:
    needs: convert-markdown
    if: false  # ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'publish' }}
    runs-on: ubuntu-latest
    steps:
      - name: Get artifacts
        uses: actions/download-artifact@v4
        with:
          name: devto_output
          path: tmp

      - name: Upload to Dev.to
        uses: philnewm/blog-upload@main
        with:
          markdown_file_path: tmp/${{ env.FILE_NAME }}
          service: "devto"
          key: ${{ secrets.DEVTO_KEY }}
          canonical_url: 
          description: "This article is about using Vagrant and VirtualBox with Molecule to test Ansible roles."
          publish: False

...
